#!/usr/bin/env python3
"""Lift the per-era flag artwork out of the 210 flag pages into one file.

WHY THIS EXISTS. flag-eras.json already gives the map every era's dates and
polity — 1,471 of them — but no picture. The artwork was only ever inside the
flag pages themselves, as inline SVG in `.entry > .card > .card-head >
.flag-box`, which meant the map could say "Kingdom of Croatia, 1102–1420" and
could not show the flag it flew. The right rail beside the map is a column of
flags; without this file it would be a column of years.

THE REGEX THAT COST AN HOUR. `<div class="entry" id="era-…">` is the Croatian
spelling. Every other page writes `<div class="entry" data-n="12" id="era-…">`,
so a pattern requiring class and id to be adjacent matches Croatia and nothing
else — it reported 18 eras with artwork out of 1,461 and looked plausible
enough to act on. `[^>]*` between them is the whole fix. Kept as a named
pattern with this note so the next person to touch it does not narrow it again.

Output is keyed slug -> era id -> svg, which is the shape the rail indexes by,
and carries no dates or polity names: those live in flag-eras.json and having
them in two files is how they drift apart.
"""
import json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FLAGS = ROOT / "site" / "public" / "flags"
# data/, not site/public/: this is a SOURCE OF TRUTH, committed, and build.py
# copies it out — the same arrangement as its sibling data/flag-eras.json.
# Written straight into public/ it was regenerated by nobody, gitignored by
# nothing, and would have 404'd on the deployed site the moment the country
# flag band asked for it.
OUT = ROOT / "data" / "era-flags.json"

# class, THEN anything, THEN id. See the note above.
ENTRY = re.compile(r'<div class="entry"[^>]*id="(era-[^"]+)"[^>]*>(.*?)'
                   r'(?=<div class="entry"|<footer|\Z)', re.S)
FLAGBOX = re.compile(r'<div class="flag-box">\s*(<svg.*?</svg>)', re.S)
# Dropped on the way out, FROM THE OPENING <svg> TAG AND NOWHERE ELSE: the
# browser does not need the namespace for inline SVG, and a fixed width/height
# on the root would beat the rail's own sizing.
#
# THE BUG THIS COMMENT EXISTS FOR. The first version applied this to the whole
# string, which also stripped width and height from every <rect> inside it —
# so `<rect width="300" height="66.7" fill="#a4302a"/>` became `<rect
# fill="#a4302a"/>`, a rectangle of zero by zero. The file extracted cleanly,
# the counts were right, the rail rendered nine flag-shaped boxes, and every
# one of them was empty. Only the root tag is rewritten now.
STRIP = re.compile(r'\s(?:xmlns(?::\w+)?|width|height)="[^"]*"')
SVG_OPEN = re.compile(r"<svg[^>]*>")
WS = re.compile(r">\s+<")


def clean(svg: str) -> str:
    """Rewrite only the root <svg ...> tag; leave every child untouched."""
    svg = SVG_OPEN.sub(lambda m: STRIP.sub("", m.group(0)), svg, count=1)
    return WS.sub("><", svg).strip()


def main() -> int:
    pages = sorted(FLAGS.glob("*-flags.html"))
    if not pages:
        print(f"no flag pages under {FLAGS}", file=sys.stderr)
        return 1

    out, art, bare = {}, 0, 0
    for page in pages:
        html = page.read_text(encoding="utf-8")
        slug = page.stem
        for eid, body in ENTRY.findall(html):
            hit = FLAGBOX.search(body)
            if not hit:
                bare += 1
                continue
            out.setdefault(slug, {})[eid] = clean(hit.group(1))
            art += 1

    doc = {
        "note": ("Per-era flag artwork, lifted from the flag pages by "
                 "scripts/extract-era-flags.py. Keyed slug -> era id -> inline "
                 "SVG. Dates and polity names are NOT here: they live in "
                 "flag-eras.json, and duplicating them is how two files drift."),
        # The wording matters: check-data.py requires every licence string in
# data/ to be named on /data/, so a reuser is told what they are taking.
# This is the same declaration data/flag-eras.json carries, because it is
# the same provenance — both come out of the project's own flag pages.
        "licence": "This atlas's own compilation",
        "counts": {"countries": len(out), "eras": art, "erasWithoutArt": bare},
        "art": out,
    }
    OUT.write_text(json.dumps(doc, separators=(",", ":")), encoding="utf-8")
    kb = OUT.stat().st_size / 1024
    print(f"{art:,} era flags from {len(out)} countries -> {OUT.name} ({kb:,.0f} KB)")
    if bare:
        print(f"{bare} era(s) carry no artwork; the rail falls back to the year alone")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
